Add method for GET /api/cloud_user
aotuai/brainframe-python pull request #19
Opened 2021-05-27 21:08 UTC by velovix

Adds a method for an API that allows clients to get information on the currently logged-in cloud user. The server returns a 404 when a user is not logged in, but this method returns `None` in this case instead.

2021-05-27 21:25 UTC, BryceBeagle commented
It might be better to call this `get_current_cloud_user` or something? See just the endpoint makes me think it should be something that takes a user_id as an argument and returns info about that user.

2021-05-27 23:01 UTC, apockill approved these changes

2021-05-28 18:53 UTC, velovix commented
@BryceBeagle Sounds reasonable

2021-05-28 18:58 UTC, BryceBeagle requested changes

2021-05-28 18:58 UTC, BryceBeagle commented on brainframe/api/stubs/cloud_users.py
> +            return None
Nitpicky change. `.from_dict` can't raise a `CloudUserNotFoundError`

```suggestion
        try:
            data, _ = self._get_json(req, timeout=timeout)
        except CloudUserNotFoundError:
            return None
        else:
            return CloudUserInfo.from_dict(data)
```

2021-05-28 19:00 UTC, velovix commented on brainframe/api/stubs/cloud_users.py
> +            return None
Good point

2021-05-28 19:01 UTC, BryceBeagle approved these changes

2021-05-28 19:15 UTC, merged