Add support for the GET /api/oauth2_info API
aotuai/brainframe-python pull request #24
Opened 2021-09-23 20:26 UTC by velovix

2021-09-23 23:40 UTC, apockill approved these changes

2021-09-24 00:35 UTC, BryceBeagle requested changes

2021-09-24 00:35 UTC, BryceBeagle commented on brainframe/api/bf_codecs/oauth2_codecs.py
> +    """Necessary information to start an OAuth2 flow on behalf of the BrainFrame server
```suggestion
    """Information necessary to start an OAuth2 flow on behalf of the BrainFrame server
```

2021-09-24 00:42 UTC, BryceBeagle approved these changes

2021-09-24 00:45 UTC, merged